sudo: false
language: ruby
rvm:
  - 1.8.7
  - ree
  - 1.9.2
  - 1.9.3
  - 2.0.0-p648
  - 2.1.7
  - 2.2.3
  - 2.3.5
  - 2.4.0
  - 2.4.2
  - ruby-head
notifications:
  recipients:
    - thomas@slash7.com
